---
- name: Ensure apache is installed and started via role
  hosts: localhost
  become: yes
  roles:
    - apache-simple

  tasks:

   - name: build a new docker image
     command: "docker build -t apache-simple ."
     tags:
        - container

   - name: Tag and push to registry
     docker_image:
       name: apache-simple
       repository: 172.16.22.48:5000/student1/apache-simple
       push: yes
       source: local
       tag: latest
     tags:
        - container
