---
# tasks file for gogs
- name: install docker-py requirements
  pip:
    name: docker-py
    state: present
    extra_args: --trusted-host pypi.org --trusted-host files.pythonhosted.org

- name: pull the GOGS and MariaDB images
  docker_image:
    name: "{{ item }}"
    state: present
    with_items:
      - gogs/gogs
      - mariadb

- name: start the GOGS container
  docker_container:
    name: gogs
    image: gogs/gogs
    ports:
      - "8081:3000"
      - "10022:22"
    restart_policy: always

- name: start the MariaDB container
  docker_container:
    name: mariadb
    image: mariadb
    env:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_DATABASE: gogs
    exposed_ports:
      - "3306"
    restart_policy: always
